name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.0.12
  - seaborn=0.11.1
  - pandas=1.5.3
  - pip=20.3.3
  - ydata-profiling=4.1.1
  - pyarrow=11.0.0
  - notebook=6.4.0
  - pip:
      - wandb==0.14.0