name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.5.3
  - pip=20.3.3
  - scikit-learn=1.2.2
  - matplotlib==3.7.1
  - plotly==5.12.0
  - pillow=9.4.0
  - mlflow=2.2.2
  - pip:
      - wandb==0.14.0
