name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.28.2
  - pip=20.3.3
  - mlflow=2.2.2
  - hydra-core=1.0.6
  - pip:
      - wandb==0.14.0
      - hydra-joblib-launcher==1.1.2
